version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/Xenode
      - MONGODB_LOGS_URI=mongodb://mongo-logs:27017/Xenode-logs
      - NEXT_TELEMETRY_DISABLED=1
      # Optional: PostHog
      - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
      - POSTHOG_KEY=${POSTHOG_KEY}
      - NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
    depends_on:
      - mongo
      - mongo-logs

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  mongo-logs:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongo-logs-data:/data/db

volumes:
  mongo-data:
  mongo-logs-data:
