services:
  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    restart: unless-stopped
    environment:
      DRIVE_URL: ${DRIVE_URL}
      PHOTOS_URL: ${PHOTOS_URL}
      CRON_SECRET: ${CRON_SECRET}

